// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0yqwGBz4wEu6JjZSjptlDXvWvaLOA6FQ',
    appId: '1:432692636064:web:207407eb2b4c93f60b9cc5',
    messagingSenderId: '432692636064',
    projectId: 'chat-apps-bce9d',
    authDomain: 'chat-apps-bce9d.firebaseapp.com',
    storageBucket: 'chat-apps-bce9d.appspot.com',
    measurementId: 'G-BT64KDBM8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW4tyeMiS6m9mX_Wk3Ph2UHQiewAeKy_Q',
    appId: '1:432692636064:android:0c421496f515195c0b9cc5',
    messagingSenderId: '432692636064',
    projectId: 'chat-apps-bce9d',
    storageBucket: 'chat-apps-bce9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB33BsUuouW4FcxCjymU1i-6NP-1LgW_Z4',
    appId: '1:432692636064:ios:3934c64159320a8a0b9cc5',
    messagingSenderId: '432692636064',
    projectId: 'chat-apps-bce9d',
    storageBucket: 'chat-apps-bce9d.appspot.com',
    iosClientId: '432692636064-bre65ot187l1ca1n2q584aqjrs49iv5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB33BsUuouW4FcxCjymU1i-6NP-1LgW_Z4',
    appId: '1:432692636064:ios:d88a71348427468a0b9cc5',
    messagingSenderId: '432692636064',
    projectId: 'chat-apps-bce9d',
    storageBucket: 'chat-apps-bce9d.appspot.com',
    iosClientId: '432692636064-peff3ir1bk4bcjv825lfgnge5v31gp5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
